# Generated by Django 5.1rc1 on 2024-07-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_food_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Опубликовано'),
        ),
    ]
