# Generated by Django 5.1rc1 on 2024-07-31 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_category_food_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='cat',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='food.category', verbose_name='Категория'),
        ),
    ]
