# Generated by Django 5.1rc1 on 2024-08-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
