# Generated by Django 5.1rc1 on 2024-08-17 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_food_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagpost',
            old_name='tag',
            new_name='name',
        ),
    ]
