# Generated by Django 5.1rc1 on 2024-08-17 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_rename_tag_tagpost_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagpost',
            old_name='name',
            new_name='tag',
        ),
    ]
